# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3c599deecd56b64fbdd78cb8702250aab003c5d7ec0b44c7059580a5c574a03c5ffd72408445cb7f34cfae461d2b8fe6dde8a17e49b2c040e4c62fc87dce4c44

test:
  secret_key_base: 44db71a49616e2adc85a5e2e254488832e8169410c754e250ad6537510f34325a09b84046fd2a2d4c474a322f7d21ccfb5039898d08f7e0e4f6af8ed653ad671

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
